FROM i386/python:3.7-buster
ENV PYTHONUNBUFFERED 1
ENV DEBIAN_FRONTEND noninteractive

MAINTAINER Andres Gomez Ramirez @kuronosec

RUN apt-get update && \
    apt-get install -y  build-essential libssl1.1 libnss3 libssl-dev libffi-dev libnss3-dev dh-make gem2deb npm2deb

RUN pip install --trusted-host pypi.python.org --no-cache-dir  --upgrade pip && \
    pip install pyinstaller


COPY requirements.txt /tmp/requirements.txt
RUN pip install --trusted-host pypi.python.org --no-cache-dir -r /tmp/requirements.txt

COPY src /zk_firma_digital_base

COPY builder/debian/copyright /tmp/copyright
COPY builder/debian/postinst /tmp/postinst

COPY builder/entrypoint_debian.sh  /entrypoint.sh 
ENTRYPOINT /entrypoint.sh 
